sudo: required
services:
  - docker

before_install:
  - docker build -t 96ankur/docker-react -f Dockerfile.dev .

script:
  - docker run 96ankur/docker-react npm run test -- --coverage  # -- --coverage forces npm to exit when
                                                                #  tests are executed for the first time 

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-957689471499"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"